version: '3.2'

services:
    php:
        build: ./.docker/php
        volumes:
            - ./:/var/www/app:cached
            - ./.docker/php/php.dev.ini:/usr/local/etc/php/php.ini
            - ./.docker/php/default.conf:/etc/apache2/sites-available/000-default.conf
            - ./.docker/php/default.conf:/etc/apache2/sites-enabled/000-default.conf
        ports:
            - 8081:80
        depends_on:
            - mysql

    mysql:
        image: mysql/mysql-server:5.6
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_ROOT_HOST=%
    
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql