# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    App\Entity\User: plaintext

  role_hierarchy:
      # Un admin hérite des droits d'auteur et de modérateur
      ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
      # On garde ce rôle superadmin, il nous resservira par la suite
      ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main_login:
        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
        pattern:   ^/login$
        anonymous: true # On autorise alors les anonymes sur ce pare-feu
    main:
      pattern:   ^/
      anonymous: true
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     login

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
